manifest:
  version: '1.2'
  remotes:
  - name: fork
    url-base: https://github.com/Haonan-Shi
  defaults:
    remote: fork
  projects:
  - name: zephyr
    repo-path: zephyr
    revision: dfa613d207b9234519ec93481812b3a09955bcee
    path: zephyr
    west-commands: scripts/west-commands.yml
    import:
      file: test.yml
      path-prefix: zephyrproject
      name-allowlist:
      - cmsis
      - tinycrypt
      - mbedtls
      - fatfs
  - name: honeygui
    repo-path: HoneyGUI
    revision: 59c0bdd6a8466911de39225471f11a78cbc84309
    path: zephyrproject/modules/honeygui
  - name: lvgl
    repo-path: lvgl
    revision: 491c579e0dafb49917100d45510e0d741a89d116
    path: zephyrproject/modules/lvgl
  - name: hal_realtek
    repo-path: zephyr-hal
    revision: 1320586305c4f70456d211fd91c60d18b5bffbb7
    path: zephyrproject/modules/hal/realtek
  - name: display
    repo-path: display
    revision: add4f71655376ac3dc264dfcbcb3d65bf917275b
    path: zephyrproject/modules/display
  self:
    path: zephyrproject/realtek-app
    userdata:
      product: watch
      version: v1.14.3.2
